---

roles:
  - src: https://github.com/companieshouse/ansible-role-mounted-volume
    name: mounted-volume
    version: "1.0.5"

  - src: https://github.com/companieshouse/ansible-role-epel
    name: epel
    version: 3.0.4

  - src: https://github.com/geerlingguy/ansible-role-pip
    name: pip
    version: "2.0.0"

  - src: https://github.com/companieshouse/ansible-role-docker
    name: docker
    version: "3.0.0"

  - src: https://github.com/cloudalchemy/ansible-node-exporter
    name: prometheus-node-exporter
    version: "0.22.0"
